package com.kq.gob.Gob;

public enum TokenType {
    // Single-character tokens.
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, LEFT_SQUARE, RIGHT_SQUARE,
    COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR, PERCENT,
    COMPOUND_MINUS, COMPOUND_PLUS, COMPOUND_SLASH, COMPOUND_STAR, COMPOUND_PERCENT,
    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
    // Literals.
    IDENTIFIER, STRING, NUMBER,
    // Keywords.
    AND, CLASS, EXTENDS, ELSE,ELSE_IF, FALSE, FUN, FOR, IF, NIL, OR,
    PRINTLN, PRINT, RETURN, SUPER, THIS, TRUE, VAR, WHILE, LENGTH,
    EOF
}